import type { DashboardViewModelSource } from "./dashboard.prototype-data.mapper"
import { createDashboardReportingSnapshot } from "./model/reporting"

const canonicalReviewTotal = 1_248

export const dashboardPrototypeData = {
  profileTasks: [
    {
      actionLabel: "Review images",
      description: "The public gallery does not yet cover every clinic area expected for a complete profile.",
      destination: "gallery",
      destinationLabel: "Open image gallery",
      id: "missing-images",
      label: "Missing images",
      priority: "High",
      visibility: "always",
    },
    {
      actionLabel: "Review team",
      description: "Two doctor profiles still need review before the public team section is complete.",
      destination: "team",
      destinationLabel: "Open doctors and team",
      id: "open-doctor-profiles",
      label: "Open doctor profiles",
      priority: "Medium",
      visibility: "always",
    },
    {
      actionLabel: "View details",
      description: "Required certificates have not yet been added to the clinic profile.",
      id: "certificates-required",
      label: "Certificates required",
      priority: "High",
      visibility: "full-interface",
    },
    {
      actionLabel: "View details",
      description: "One certificate is approaching its expiry date and needs review.",
      id: "certificate-expiry",
      label: "Certificate expiry",
      priority: "Low",
      visibility: "full-interface",
    },
  ],
  rating: {
    categories: ["Hair transplant", "Dental implants", "Laser eye surgery"],
    count: canonicalReviewTotal,
    pendingResponses: 1,
    value: 4.8,
  },
  reporting: {
    "7 days": createDashboardReportingSnapshot({
      changes: {
        contacts: "-7.7%",
        impressions: "+8.4%",
        inquiries: "+25.0%",
        profileViews: "+10.1%",
      },
      chart: {
        comparison: "+10.1% vs. previous 7 days",
        description:
          "Daily profile views across the selected 7 days total 848. The highest day has 135 profile views.",
        points: [
          { axisLabel: "Oct 6", dateLabel: "October 6", value: 103 },
          { axisLabel: "Oct 7", dateLabel: "October 7", value: 111 },
          { axisLabel: "Oct 8", dateLabel: "October 8", value: 119 },
          { axisLabel: "Oct 9", dateLabel: "October 9", value: 117 },
          { axisLabel: "Oct 10", dateLabel: "October 10", value: 129 },
          { axisLabel: "Oct 11", dateLabel: "October 11", value: 135 },
          { axisLabel: "Oct 12", dateLabel: "October 12", value: 134 },
        ],
      },
      period: "7 days",
      reviewActivity: "1 new review in the last 7 days",
      totals: {
        contacts: 12,
        impressions: 4_680,
        inquiries: 5,
        profileViews: 848,
        uniqueVisitors: 543,
      },
    }),
    "30 days": createDashboardReportingSnapshot({
      changes: {
        contacts: "-2.1%",
        impressions: "+5.2%",
        inquiries: "+8.4%",
        profileViews: "+12.0%",
      },
      chart: {
        comparison: "+12.0% vs. previous 30 days",
        description:
          "Daily profile views across the selected 30 days total 3,284. Date labels are shown at regular intervals to keep the chart readable.",
        points: [
          { axisLabel: "Sep 13", dateLabel: "September 13", value: 94 },
          { dateLabel: "September 14", value: 98 },
          { dateLabel: "September 15", value: 102 },
          { dateLabel: "September 16", value: 99 },
          { dateLabel: "September 17", value: 106 },
          { dateLabel: "September 18", value: 105 },
          { dateLabel: "September 19", value: 110 },
          { dateLabel: "September 20", value: 101 },
          { dateLabel: "September 21", value: 104 },
          { axisLabel: "Sep 22", dateLabel: "September 22", value: 108 },
          { dateLabel: "September 23", value: 104 },
          { dateLabel: "September 24", value: 99 },
          { dateLabel: "September 25", value: 101 },
          { dateLabel: "September 26", value: 105 },
          { dateLabel: "September 27", value: 108 },
          { dateLabel: "September 28", value: 103 },
          { dateLabel: "September 29", value: 110 },
          { dateLabel: "September 30", value: 114 },
          { dateLabel: "October 1", value: 107 },
          { axisLabel: "Oct 2", dateLabel: "October 2", value: 111 },
          { dateLabel: "October 3", value: 116 },
          { dateLabel: "October 4", value: 112 },
          { dateLabel: "October 5", value: 118 },
          { dateLabel: "October 6", value: 122 },
          { dateLabel: "October 7", value: 115 },
          { dateLabel: "October 8", value: 120 },
          { dateLabel: "October 9", value: 124 },
          { dateLabel: "October 10", value: 119 },
          { dateLabel: "October 11", value: 128 },
          { axisLabel: "Oct 12", dateLabel: "October 12", value: 121 },
        ],
      },
      period: "30 days",
      reviewActivity: "5 new reviews in the last 30 days",
      totals: {
        contacts: 42,
        impressions: 18_420,
        inquiries: 16,
        profileViews: 3_284,
        uniqueVisitors: 2_105,
      },
    }),
    "90 days": createDashboardReportingSnapshot({
      changes: {
        contacts: "+4.4%",
        impressions: "+11.8%",
        inquiries: "+6.7%",
        profileViews: "+9.6%",
      },
      chart: {
        comparison: "+9.6% vs. previous 90 days",
        description:
          "Weekly profile views across the selected 90 days total 9,410. The chart aggregates daily activity into 13 weekly points.",
        points: [
          { axisLabel: "Jul 14", dateLabel: "Week of July 14", value: 590 },
          { dateLabel: "Week of July 21", value: 628 },
          { axisLabel: "Jul 28", dateLabel: "Week of July 28", value: 655 },
          { dateLabel: "Week of August 4", value: 674 },
          { axisLabel: "Aug 11", dateLabel: "Week of August 11", value: 702 },
          { dateLabel: "Week of August 18", value: 721 },
          { axisLabel: "Aug 25", dateLabel: "Week of August 25", value: 735 },
          { dateLabel: "Week of September 1", value: 748 },
          { axisLabel: "Sep 8", dateLabel: "Week of September 8", value: 760 },
          { dateLabel: "Week of September 15", value: 777 },
          { axisLabel: "Sep 22", dateLabel: "Week of September 22", value: 791 },
          { dateLabel: "Week of September 29", value: 806 },
          { axisLabel: "Oct 6", dateLabel: "Week of October 6", value: 823 },
        ],
      },
      period: "90 days",
      reviewActivity: "17 new reviews in the last 90 days",
      totals: {
        contacts: 118,
        impressions: 53_680,
        inquiries: 45,
        profileViews: 9_410,
        uniqueVisitors: 6_006,
      },
    }),
  },
} satisfies DashboardViewModelSource
