import type { DashboardSnapshot } from "./model/dashboard-snapshot"
import { createDashboardReportingSnapshot } from "./model/reporting"

const canonicalReviewTotal = 1_248

export const dashboardPrototypeData = {
  profileTasks: [
    {
      actionLabel: "Review images",
      description: "The public gallery does not yet cover every clinic area expected for a complete profile.",
      destination: "gallery",
      destinationLabel: "Open image gallery",
      id: "missing-images",
      label: "Missing images",
      priority: "High",
      visibility: "always",
    },
    {
      actionLabel: "Review team",
      description: "Two doctor profiles still need review before the public team section is complete.",
      destination: "team",
      destinationLabel: "Open doctors and team",
      id: "open-doctor-profiles",
      label: "Open doctor profiles",
      priority: "Medium",
      visibility: "always",
    },
    {
      actionLabel: "View details",
      description: "Required certificates have not yet been added to the clinic profile.",
      id: "certificates-required",
      label: "Certificates required",
      priority: "High",
      visibility: "full-interface",
    },
    {
      actionLabel: "View details",
      description: "One certificate is approaching its expiry date and needs review.",
      id: "certificate-expiry",
      label: "Certificate expiry",
      priority: "Low",
      visibility: "full-interface",
    },
  ],
  rating: {
    categories: ["Hair transplant", "Dental implants", "Laser eye surgery"],
    count: canonicalReviewTotal,
    pendingResponses: 1,
    value: 4.8,
  },
  reporting: {
    "7 days": createDashboardReportingSnapshot({
      changes: {
        contacts: "-7.7%",
        impressions: "+8.4%",
        inquiries: "+25.0%",
        views: "+10.1%",
      },
      chart: {
        cadence: "daily",
        dates: [
          { axisLabel: "Oct 6", dateLabel: "October 6" },
          { axisLabel: "Oct 7", dateLabel: "October 7" },
          { axisLabel: "Oct 8", dateLabel: "October 8" },
          { axisLabel: "Oct 9", dateLabel: "October 9" },
          { axisLabel: "Oct 10", dateLabel: "October 10" },
          { axisLabel: "Oct 11", dateLabel: "October 11" },
          { axisLabel: "Oct 12", dateLabel: "October 12" },
        ],
        series: {
          contacts: [1, 1, 2, 2, 2, 2, 2],
          impressions: [568, 613, 657, 646, 712, 745, 739],
          inquiries: [0, 0, 1, 1, 1, 1, 1],
          views: [103, 111, 119, 117, 129, 135, 134],
        },
      },
      period: "7 days",
      reviewActivity: "1 new review in the last 7 days",
      totals: {
        contacts: 12,
        impressions: 4_680,
        inquiries: 5,
        profileViews: 848,
        uniqueVisitors: 543,
      },
    }),
    "30 days": createDashboardReportingSnapshot({
      changes: {
        contacts: "-2.1%",
        impressions: "+5.2%",
        inquiries: "+8.4%",
        views: "+12.0%",
      },
      chart: {
        cadence: "daily",
        dates: [
          { axisLabel: "Sep 13", dateLabel: "September 13" },
          { dateLabel: "September 14" },
          { dateLabel: "September 15" },
          { dateLabel: "September 16" },
          { dateLabel: "September 17" },
          { dateLabel: "September 18" },
          { dateLabel: "September 19" },
          { dateLabel: "September 20" },
          { dateLabel: "September 21" },
          { axisLabel: "Sep 22", dateLabel: "September 22" },
          { dateLabel: "September 23" },
          { dateLabel: "September 24" },
          { dateLabel: "September 25" },
          { dateLabel: "September 26" },
          { dateLabel: "September 27" },
          { dateLabel: "September 28" },
          { dateLabel: "September 29" },
          { dateLabel: "September 30" },
          { dateLabel: "October 1" },
          { axisLabel: "Oct 2", dateLabel: "October 2" },
          { dateLabel: "October 3" },
          { dateLabel: "October 4" },
          { dateLabel: "October 5" },
          { dateLabel: "October 6" },
          { dateLabel: "October 7" },
          { dateLabel: "October 8" },
          { dateLabel: "October 9" },
          { dateLabel: "October 10" },
          { dateLabel: "October 11" },
          { axisLabel: "Oct 12", dateLabel: "October 12" },
        ],
        series: {
          contacts: [
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
          ],
          impressions: [
            527, 550, 572, 555, 595, 589, 617, 567, 583, 606, 583, 555, 566, 589, 606, 578, 617, 639, 600,
            623, 651, 628, 662, 684, 645, 673, 696, 667, 718, 679,
          ],
          inquiries: [
            0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          ],
          views: [
            94, 98, 102, 99, 106, 105, 110, 101, 104, 108, 104, 99, 101, 105, 108, 103, 110, 114, 107, 111,
            116, 112, 118, 122, 115, 120, 124, 119, 128, 121,
          ],
        },
      },
      period: "30 days",
      reviewActivity: "5 new reviews in the last 30 days",
      totals: {
        contacts: 42,
        impressions: 18_420,
        inquiries: 16,
        profileViews: 3_284,
        uniqueVisitors: 2_105,
      },
    }),
    "90 days": createDashboardReportingSnapshot({
      changes: {
        contacts: "+4.4%",
        impressions: "+11.8%",
        inquiries: "+6.7%",
        views: "+9.6%",
      },
      chart: {
        cadence: "weekly",
        dates: [
          { axisLabel: "Jul 14", dateLabel: "Week of July 14" },
          { dateLabel: "Week of July 21" },
          { axisLabel: "Jul 28", dateLabel: "Week of July 28" },
          { dateLabel: "Week of August 4" },
          { axisLabel: "Aug 11", dateLabel: "Week of August 11" },
          { dateLabel: "Week of August 18" },
          { axisLabel: "Aug 25", dateLabel: "Week of August 25" },
          { dateLabel: "Week of September 1" },
          { axisLabel: "Sep 8", dateLabel: "Week of September 8" },
          { dateLabel: "Week of September 15" },
          { axisLabel: "Sep 22", dateLabel: "Week of September 22" },
          { dateLabel: "Week of September 29" },
          { axisLabel: "Oct 6", dateLabel: "Week of October 6" },
        ],
        series: {
          contacts: [7, 8, 8, 9, 9, 9, 9, 9, 10, 10, 10, 10, 10],
          impressions: [3366, 3582, 3737, 3845, 4005, 4113, 4193, 4267, 4335, 4432, 4512, 4598, 4695],
          inquiries: [3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4],
          views: [590, 628, 655, 674, 702, 721, 735, 748, 760, 777, 791, 806, 823],
        },
      },
      period: "90 days",
      reviewActivity: "17 new reviews in the last 90 days",
      totals: {
        contacts: 118,
        impressions: 53_680,
        inquiries: 45,
        profileViews: 9_410,
        uniqueVisitors: 6_006,
      },
    }),
  },
} satisfies DashboardSnapshot
