import type { ReviewsSnapshot } from "@/features/clinic-dashboard/reviews/public"

export const berlinCharlottenburgReviews = {
  distribution: [
    { count: 355, percent: 73, stars: 5 },
    { count: 90, percent: 18.5, stars: 4 },
    { count: 25, percent: 5.1, stars: 3 },
    { count: 11, percent: 2.3, stars: 2 },
    { count: 5, percent: 1.1, stars: 1 },
  ],
  items: [
    {
      age: "Today",
      author: "Eva Lindner",
      body: "The consultation was personal and the treatment options were explained with useful comparisons.",
      createdAt: "2026-07-19T07:20:00.000Z",
      id: "berlin-charlottenburg-review-eva-lindner",
      initials: "EL",
      internalNotes: [],
      pendingResponse: {
        response: "Thank you. We are pleased that the comparison of options was useful.",
        status: "pending-moderation",
        submittedAt: "2026-07-19T10:00:00.000Z",
      },
      rating: 5,
      revision: 2,
      status: "Open",
      treatment: "Ceramic veneers",
    },
    {
      age: "3 days ago",
      author: "Tobias Kramer",
      body: "A calm appointment, clear timings, and helpful follow-up information.",
      createdAt: "2026-07-16T16:10:00.000Z",
      id: "berlin-charlottenburg-review-tobias-kramer",
      initials: "TK",
      internalNotes: [],
      publishedResponse: "Thank you for your feedback about the appointment and follow-up.",
      rating: 5,
      revision: 2,
      status: "Answered",
      treatment: "Laser teeth whitening",
    },
    {
      age: "5 days ago",
      author: "Anonymous patient",
      body: "The review is hidden while a privacy concern is assessed.",
      createdAt: "2026-07-14T12:40:00.000Z",
      id: "berlin-charlottenburg-review-appeal-privacy",
      initials: "AP",
      internalNotes: [],
      appealCase: {
        detail: "The review contains appointment details that may identify another person.",
        events: [
          {
            id: "berlin-charlottenburg-appeal-event-1",
            occurredAt: "2026-07-18T09:15:00.000Z",
            status: "submitted",
            type: "appeal-submitted",
          },
        ],
        reason: "Privacy concern",
        reference: "APPEAL-BERLIN-CHARLOTTENBURG-PRIVACY",
        status: "submitted",
        submittedAt: "2026-07-18T09:15:00.000Z",
        updatedAt: "2026-07-18T09:15:00.000Z",
      },
      rating: 2,
      revision: 2,
      status: "Open",
      treatment: "Dermatology",
    },
    {
      age: "1 week ago",
      author: "Katharina Busch",
      body: "The reception team was attentive and the clinic felt well organised.",
      createdAt: "2026-07-11T10:00:00.000Z",
      id: "berlin-charlottenburg-review-katharina-busch",
      initials: "KB",
      internalNotes: [],
      publishedResponse: "Thank you. We have passed your feedback to the reception team.",
      rating: 5,
      revision: 1,
      status: "Answered",
      treatment: "Skin analysis",
    },
    {
      age: "2 weeks ago",
      author: "Robert Fink",
      body: "The advice was useful, but I would have appreciated a shorter wait for the written summary.",
      createdAt: "2026-07-04T13:30:00.000Z",
      id: "berlin-charlottenburg-review-robert-fink",
      initials: "RF",
      internalNotes: [],
      rating: 4,
      revision: 1,
      status: "Open",
      treatment: "Aesthetic dentistry",
    },
    {
      age: "1 month ago",
      author: "Lea Sonntag",
      body: "Professional consultation and a reassuring explanation of the alternatives.",
      createdAt: "2026-06-20T08:15:00.000Z",
      id: "berlin-charlottenburg-review-lea-sonntag",
      initials: "LS",
      internalNotes: [],
      publishedResponse: "Thank you for describing your consultation experience.",
      rating: 5,
      revision: 1,
      status: "Answered",
      treatment: "Ceramic veneers",
    },
  ],
  rating: 4.6,
  referenceTime: "2026-07-19T10:00:00.000Z",
  total: 486,
} satisfies ReviewsSnapshot
