import type { ReviewsSnapshot } from "@/features/clinic-dashboard/reviews/public"

export const berlinMitteReviews = {
  distribution: [
    { count: 1_061, percent: 85, stars: 5 },
    { count: 125, percent: 10, stars: 4 },
    { count: 37, percent: 3, stars: 3 },
    { count: 17, percent: 1.4, stars: 2 },
    { count: 8, percent: 0.6, stars: 1 },
  ],
  items: [
    {
      age: "1 day ago",
      author: "Clara Hoffmann",
      body: "The consultation was clearly structured and the team explained every next step without rushing me.",
      createdAt: "2026-07-18T09:10:00.000Z",
      id: "berlin-mitte-review-clara-hoffmann",
      initials: "CH",
      internalNotes: [],
      pendingResponse: {
        response: "Thank you for your feedback. We have shared it with the consultation team.",
        status: "pending-moderation",
        submittedAt: "2026-07-19T10:00:00.000Z",
      },
      publishedResponse: "Thank you for taking the time to describe your consultation.",
      rating: 5,
      revision: 3,
      status: "Answered",
      treatment: "Hair transplant",
    },
    {
      age: "2 days ago",
      author: "Anonymous patient",
      body: "The treatment was professional, but the waiting time at reception was longer than expected.",
      createdAt: "2026-07-17T14:30:00.000Z",
      id: "berlin-mitte-review-open-waiting-time",
      initials: "AP",
      internalNotes: [],
      rating: 3,
      revision: 1,
      status: "Open",
      treatment: "Dermatology",
    },
    {
      age: "4 days ago",
      author: "Maren Scholz",
      body: "The review is hidden while the clinic-location assignment is assessed.",
      createdAt: "2026-07-15T11:00:00.000Z",
      id: "berlin-mitte-review-appeal-location",
      initials: "MS",
      internalNotes: [],
      appealCase: {
        detail: "The appointment referenced in the review was recorded for another provider.",
        events: [
          {
            id: "berlin-mitte-appeal-event-1",
            occurredAt: "2026-07-18T08:00:00.000Z",
            status: "submitted",
            type: "appeal-submitted",
          },
          {
            fromStatus: "submitted",
            id: "berlin-mitte-appeal-event-2",
            occurredAt: "2026-07-18T13:00:00.000Z",
            toStatus: "under-review",
            type: "appeal-status-changed",
          },
        ],
        reason: "Incorrect clinic",
        reference: "APPEAL-BERLIN-MITTE-LOCATION",
        status: "under-review",
        submittedAt: "2026-07-18T08:00:00.000Z",
        updatedAt: "2026-07-18T13:00:00.000Z",
      },
      rating: 1,
      revision: 3,
      status: "Under review",
      treatment: "Unknown",
    },
    {
      age: "1 week ago",
      author: "Jonas Peters",
      body: "Friendly staff, useful preparation notes, and a very calm appointment.",
      createdAt: "2026-07-12T10:15:00.000Z",
      id: "berlin-mitte-review-jonas-peters",
      initials: "JP",
      internalNotes: [],
      publishedResponse: "Thank you for sharing your experience with our team.",
      rating: 5,
      revision: 2,
      status: "Answered",
      treatment: "Laser teeth whitening",
    },
    {
      age: "2 weeks ago",
      author: "Sofia Lang",
      body: "The information before the appointment was concise and easy to follow.",
      createdAt: "2026-07-05T08:45:00.000Z",
      id: "berlin-mitte-review-sofia-lang",
      initials: "SL",
      internalNotes: [],
      publishedResponse: "We appreciate your feedback about the preparation information.",
      rating: 5,
      revision: 1,
      status: "Answered",
      treatment: "Skin analysis",
    },
    {
      age: "1 month ago",
      author: "Anonymous patient",
      body: "Good consultation overall, although appointment coordination required an extra call.",
      createdAt: "2026-06-18T15:00:00.000Z",
      id: "berlin-mitte-review-open-coordination",
      initials: "AP",
      internalNotes: [],
      rating: 4,
      revision: 1,
      status: "Open",
      treatment: "Hair transplant",
    },
  ],
  rating: 4.8,
  referenceTime: "2026-07-19T10:00:00.000Z",
  total: 1_248,
} satisfies ReviewsSnapshot
