import type { ReviewsSnapshot } from "@/features/clinic-dashboard/reviews/public"

export const antalyaLaraReviews = {
  distribution: [
    { count: 84, percent: 91.3, stars: 5 },
    { count: 6, percent: 6.5, stars: 4 },
    { count: 1, percent: 1.1, stars: 3 },
    { count: 1, percent: 1.1, stars: 2 },
    { count: 0, percent: 0, stars: 1 },
  ],
  items: [
    {
      age: "1 day ago",
      author: "Melis Güneş",
      body: "The new location is bright, quiet, and the consultation was very easy to understand.",
      createdAt: "2026-07-18T11:30:00.000Z",
      id: "antalya-lara-review-melis-gunes",
      initials: "MG",
      internalNotes: [],
      pendingResponse: {
        response: "Thank you for your feedback about the consultation and the new location.",
        status: "pending-moderation",
        submittedAt: "2026-07-19T10:00:00.000Z",
      },
      rating: 5,
      revision: 2,
      status: "Open",
      treatment: "Dermatology consultation",
    },
    {
      age: "3 days ago",
      author: "Kaan Aksu",
      body: "Helpful preparation information and a friendly, focused appointment.",
      createdAt: "2026-07-16T09:50:00.000Z",
      id: "antalya-lara-review-kaan-aksu",
      initials: "KA",
      internalNotes: [],
      publishedResponse: "Thank you for sharing your experience at our Antalya location.",
      rating: 5,
      revision: 1,
      status: "Answered",
      treatment: "Skin analysis",
    },
    {
      age: "6 days ago",
      author: "Anonymous patient",
      body: "This review is hidden while its stated treatment location is checked.",
      createdAt: "2026-07-13T14:20:00.000Z",
      id: "antalya-lara-review-appeal-location",
      initials: "AP",
      internalNotes: [],
      appealCase: {
        detail: "The treatment described was not offered at the Antalya location on the stated date.",
        events: [
          {
            id: "antalya-lara-appeal-event-1",
            occurredAt: "2026-07-18T10:10:00.000Z",
            status: "submitted",
            type: "appeal-submitted",
          },
          {
            fromStatus: "submitted",
            id: "antalya-lara-appeal-event-2",
            occurredAt: "2026-07-18T15:45:00.000Z",
            toStatus: "under-review",
            type: "appeal-status-changed",
          },
        ],
        reason: "Incorrect clinic",
        reference: "APPEAL-ANTALYA-LARA-LOCATION",
        status: "under-review",
        submittedAt: "2026-07-18T10:10:00.000Z",
        updatedAt: "2026-07-18T15:45:00.000Z",
      },
      rating: 2,
      revision: 3,
      status: "Under review",
      treatment: "Unknown",
    },
    {
      age: "1 week ago",
      author: "Nehir Kılıç",
      body: "The clinic answered my questions clearly and the visit felt well prepared.",
      createdAt: "2026-07-10T08:10:00.000Z",
      id: "antalya-lara-review-nehir-kilic",
      initials: "NK",
      internalNotes: [],
      publishedResponse: "Thank you for your kind feedback about the preparation and visit.",
      rating: 5,
      revision: 1,
      status: "Answered",
      treatment: "Dermatology consultation",
    },
    {
      age: "2 weeks ago",
      author: "Tolga Deniz",
      body: "A clear consultation in a pleasant environment with sensible next steps.",
      createdAt: "2026-07-03T12:00:00.000Z",
      id: "antalya-lara-review-tolga-deniz",
      initials: "TD",
      internalNotes: [],
      publishedResponse: "We appreciate your feedback about the consultation plan.",
      rating: 5,
      revision: 1,
      status: "Answered",
      treatment: "Skin analysis",
    },
    {
      age: "1 month ago",
      author: "Dilan Çetin",
      body: "The appointment was friendly and thorough, though the written follow-up arrived a day later.",
      createdAt: "2026-06-19T16:20:00.000Z",
      id: "antalya-lara-review-dilan-cetin",
      initials: "DÇ",
      internalNotes: [],
      rating: 4,
      revision: 1,
      status: "Open",
      treatment: "General dermatology",
    },
  ],
  rating: 4.9,
  referenceTime: "2026-07-19T10:00:00.000Z",
  total: 92,
} satisfies ReviewsSnapshot
